// Auto-generated by gonacli
'use strict';

const { spawnSync } = require('child_process');
const path = require('path');
const { join, resolve } = path;
const fs = require('fs');

const config = {
  name: "nodeminify",
  sources: ["minify.go"],
  exports: ["MinifyString","MinifyStringAsync"],
};

const rootDir = __dirname;
const isWin = process.platform === 'win32';
const nodeBin = process.execPath;
const nodeGypFromEnv = process.env.npm_config_node_gyp;
const goCmd = process.env.GO_BINARY || 'go';
const moduleRootRel = "../minify";
const moduleRoot = moduleRootRel ? resolve(rootDir, moduleRootRel) : rootDir;
const buildDir = join(rootDir, 'prebuild');
const outDir = join(rootDir, 'prebuilds');
const nodeGypBuildDir = join(rootDir, 'build');
const platformId = (() => {
  const { platformIdentifier } = require('./platform');
  return platformIdentifier();
})();
const targetDir = join(outDir, platformId);

for (const dir of [buildDir, nodeGypBuildDir, outDir]) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function run(cmd, args) {
  const result = spawnSync(cmd, args, { cwd: rootDir, stdio: 'inherit' });
  if (result.error) {
    const err = new Error(result.error.message || String(result.error));
    err.code = typeof result.error.code === 'number' ? result.error.code : 1;
    err.errno = typeof result.error.code === 'string' ? result.error.code : undefined;
    throw err;
  }
  if (result.status !== 0) {
    const statusCode = typeof result.status === 'number' ? result.status : 1;
    const err = new Error(cmd + ' ' + args.join(' ') + ' failed with code ' + statusCode);
    err.code = statusCode;
    err.status = statusCode;
    throw err;
  }
}

function tryRun(cmd, args) {
  const result = spawnSync(cmd, args, { cwd: rootDir, stdio: 'inherit' });
  if (result.error) {
    if (result.error.code === 'ENOENT') {
      return { ok: false, missing: true };
    }
    const err = new Error(result.error.message || String(result.error));
    err.code = typeof result.error.code === 'number' ? result.error.code : 1;
    throw err;
  }
  if (result.status !== 0) {
    const statusCode = typeof result.status === 'number' ? result.status : 1;
    const err = new Error(cmd + ' ' + args.join(' ') + ' failed with code ' + statusCode);
    err.code = statusCode;
    err.status = statusCode;
    throw err;
  }
  return { ok: true, missing: false };
}

function buildGo() {
  console.log('Building Go c-archive ...');
  const goCheck = tryRun(goCmd, ['version']);
  if (!goCheck.ok && goCheck.missing) {
    throw new Error('Go toolchain not found. Please install Go and ensure "' + goCmd + '" is in PATH, or set GO_BINARY to the Go executable.');
  }
  const workDir = fs.existsSync(moduleRoot) ? moduleRoot : rootDir;
  if (!fs.existsSync(workDir)) {
    throw new Error('Go module root "' + workDir + '" does not exist. Make sure Go sources are included in the installed package.');
  }

  const missingSources = [];
  for (const src of config.sources) {
    const full = join(workDir, src);
    if (!fs.existsSync(full)) {
      missingSources.push(full);
    }
  }
  if (missingSources.length > 0) {
    throw new Error('Go sources are missing from this package. Ensure the following files are published: ' + missingSources.join(', '));
  }

  const args = ['build', '-buildmode=c-archive', '-o', join(buildDir, config.name + '.a')];
  for (const src of config.sources) {
    args.push(join(workDir, src));
  }
  const result = spawnSync(goCmd, args, { cwd: workDir, stdio: 'inherit' });
  if (result.error) {
    const err = new Error('Failed to run Go build. ' + (result.error.message || String(result.error)) + ' (cwd=' + workDir + ')');
    err.code = typeof result.error.code === 'number' ? result.error.code : 1;
    err.errno = typeof result.error.code === 'string' ? result.error.code : undefined;
    throw err;
  }
  if (result.status !== 0) {
    const statusCode = typeof result.status === 'number' ? result.status : 1;
    const err = new Error('go build -buildmode=c-archive failed with code ' + statusCode);
    err.code = statusCode;
    err.status = statusCode;
    throw err;
  }
}

function patchWindowsHeader() {
  const headerPath = join(buildDir, config.name + '.h');
  if (!fs.existsSync(headerPath)) {
    throw new Error('Missing generated header file: ' + headerPath);
  }

  const patched = fs
    .readFileSync(headerPath, 'utf8')
    .split(/\r?\n/)
    .map((line) => {
      if (line.startsWith('#line 1') && line.includes('cgo-builtin-export-prolog')) {
        return '/*' + line + '*/';
      }
      if (line.startsWith('#line 1') && line.includes('cgo-gcc-export-header-prolog')) {
        return '/*' + line + '*/';
      }
      if (line.startsWith('typedef') && line.includes('GoUintptr')) {
        return '/*' + line + '*/';
      }
      if (line.startsWith('typedef') && line.includes('GoComplex64')) {
        return '/*' + line + '*/';
      }
      if (line.startsWith('typedef') && line.includes('GoComplex128')) {
        return '/*' + line + '*/';
      }
      return line;
    })
    .join('\n');

  fs.writeFileSync(headerPath, patched.endsWith('\n') ? patched : patched + '\n', 'utf8');
}

function writeDefFile() {
  const defPath = join(buildDir, config.name + '.def');
  const lines = ['EXPORTS', ...config.exports.map((name) => '  ' + name)];
  fs.writeFileSync(defPath, lines.join('\n') + '\n', 'utf8');
  return defPath;
}

function buildWindowsArtifacts(defPath) {
  const dllName = join(buildDir, config.name + '.dll');
  const goLib = join(buildDir, config.name + '.a');
  console.log('Building Windows dll/lib ...');

  run('gcc', [defPath, goLib, '-shared', '-lwinmm', '-lWs2_32', '-o', dllName, '-Wl,--out-implib,' + join(buildDir, config.name + '.dll.a')]);

  const machine = process.arch === 'ia32' ? 'X86' : 'X64';
  const libRes = tryRun('lib', ['/def:' + defPath, '/name:' + dllName, '/out:' + join(buildDir, config.name + '.lib'), '/MACHINE:' + machine]);
  if (!libRes.ok && libRes.missing) {
    const dllToolRes = tryRun('dlltool', ['-d', defPath, '-D', dllName, '-l', join(buildDir, config.name + '.lib')]);
    if (!dllToolRes.ok && dllToolRes.missing) {
      throw new Error('Missing "lib" (Visual Studio) or "dlltool" (MinGW). Install one of them to produce the import library.');
    }
  }
}

function getNodeGypRunners() {
  const runners = [];
  if (nodeGypFromEnv) {
    runners.push({ cmd: nodeBin, args: [nodeGypFromEnv] });
  }
  if (isWin) {
    runners.push({ cmd: 'node-gyp.cmd', args: [] });
    runners.push({ cmd: 'npx.cmd', args: ['node-gyp'] });
  } else {
    runners.push({ cmd: 'node-gyp', args: [] });
    runners.push({ cmd: 'npx', args: ['node-gyp'] });
  }
  return runners;
}

function buildAddon(debug) {
  const args = ['rebuild'];
  if (debug) {
    args.push('--debug');
  }
  const errors = [];
  for (const runner of getNodeGypRunners()) {
    try {
      run(runner.cmd, [...runner.args, ...args]);
      return;
    } catch (err) {
      const errno = err && err.errno ? err.errno : err && err.code ? err.code : '';
      const message = err && err.message ? err.message : String(err);
      errors.push(runner.cmd + ' ' + [...runner.args, ...args].join(' ') + ' -> ' + (errno ? errno + ' ' : '') + message);
      if (errno === 'ENOENT' || errno === 'EINVAL') {
        continue;
      }
      if (typeof err.status === 'number' || typeof err.code === 'number') {
        throw err;
      }
    }
  }
  throw new Error('Failed to run node-gyp via any runner. Tried: ' + errors.join('; '));
}

function findNodeBinary(dir) {
  if (!fs.existsSync(dir)) {
    return null;
  }
  const entries = fs.readdirSync(dir);
  for (const f of entries) {
    if (f.toLowerCase().endsWith('.node')) {
      return join(dir, f);
    }
  }
  return null;
}

function copyArtifactsToTarget() {
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  const nodeBins = [];
  const releaseDir = join(nodeGypBuildDir, 'Release');
  const debugDir = join(nodeGypBuildDir, 'Debug');
  for (const dir of [releaseDir, debugDir]) {
    if (fs.existsSync(dir)) {
      for (const f of fs.readdirSync(dir)) {
        if (f.toLowerCase().endsWith('.node')) {
          nodeBins.push(join(dir, f));
        }
      }
    }
  }

  for (const nodeBin of nodeBins) {
    const targetNode = join(targetDir, path.basename(nodeBin));
    fs.copyFileSync(nodeBin, targetNode);
    if (isWin) {
      const dllSrc = join(buildDir, config.name + '.dll');
      if (fs.existsSync(dllSrc)) {
        fs.copyFileSync(dllSrc, join(targetDir, config.name + '.dll'));
      }
    }
  }
}

function cleanupBuildDirs() {
  if (fs.existsSync(buildDir)) {
    fs.rmSync(buildDir, { recursive: true, force: true });
  }
  if (fs.existsSync(nodeGypBuildDir)) {
    fs.rmSync(nodeGypBuildDir, { recursive: true, force: true });
  }
}

(() => {
  try {
    const debug = process.argv.includes('--debug');
    if (fs.existsSync(targetDir) && findNodeBinary(targetDir)) {
      console.log('Existing build detected for', platformId, '- skipping rebuild.');
      return;
    }
    buildGo();
    if (isWin) {
      patchWindowsHeader();
      const defPath = writeDefFile();
      buildWindowsArtifacts(defPath);
    }
    buildAddon(debug);
    copyArtifactsToTarget();
    cleanupBuildDirs();
  } catch (err) {
    console.error(err && err.stack ? err.stack : err && err.message ? err.message : err);
    const exitCode = typeof err?.code === 'number' ? err.code : 1;
    process.exit(exitCode);
  }
})();
