// Auto-generated by gonode
'use strict';

function platformIdentifier() {
  const platform = process.platform;
  const arch = process.arch;
  const abi = process.versions && process.versions.modules ? process.versions.modules : 'unknown';
  return platform + '-' + arch + '-node-' + abi;
}

module.exports = {
  platformIdentifier,
};
